name: Daily Commit

on:
  schedule:
    - cron: '0 7 * * *'  # Every day at 7 AM UTC
  workflow_dispatch:      # Allows manual run

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make an empty commit
        run: |
          git config user.name "success1050"
          git config user.email "emmanuelekwunife58@gmail.com"
          git commit --allow-empty -m "chore: daily commit"
          git push
